helge17/tuxguitar

TuxGuitar-converter/src/org/herac/tuxguitar/app/tools/custom/converter/TGConverterPlugin.java, TuxGuitar-jack-ui/src/org/herac/tuxguitar/jack/console/JackConsolePlugin.java, TuxGuitar-tuner/src/org/herac/tuxguitar/app/tools/custom/tuner/TGTunerPlugin.java, TuxGuitar/src/org/herac/tuxguitar/app/tools/custom/TGCustomTool.java, TuxGuitar/src/org/herac/tuxguitar/app/tools/custom/TGToolItemPlugin.java, TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/ToolMenuItem.java
This modification enables the translation of plugins-related items in Tools/Shortcuts dialog (see the last items in list)
following translation of "Tools" menu item, an additional "label" property was created in class TGCustomTool to avoid interfering with "name" property
But... finally, just changing the value of "name" property was enough This value was already used to populate the shortcuts settings dialog
=> translation of plugins-related strings (shortcuts settings dialog)

TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGBeatImpl.java, TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGNoteImpl.java
Fix for issue #22 (sorry for that!)
Updated effect spacing in TGBeatImpl to consider bend effect, just as all other effects displayed above the tab. Absolutely necessary for Android.
Also added a check in TGNoteImpl to avoid an hypothetical null pointer exception (just a precaution)
Tested on Android, Linux SWT, Linux JFX
=> Fix incorrect vertical spacing for bend effects

TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java
This is a proposal for an evolution of tracks table horizontal scrolling, with the objective to address issue #28 
The idea is:
- when playing, to anticipate horizontal scroll of tracks table by a few measures for a better anticipation
- when scrolling, leave a few measures "behind" for continuity
On a wide screen it will leave 3 measures margin left and right. This margin is reduced if the window is so small there is not enough space for that.
This margin is only applied when playing: when *not* playing, moving with arrows or mouse should have the same behavior as before (scroll measures 1 by 1)
=> smooth horizontal scrolling of tracks table when playing

TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Selector.java
Fix for issue #39
before that, to select 1 single beat with the mouse user needs to select 2 first, then come back to keep only one
consequences:
- re-select after pasting 1 single beat doesn't work
- repeat 1 single beat only works once
note: bug is present in original implementation of "click&drag select" in 2.0beta fork
=> enable a single-beat selection

TuxGuitar/src/org/herac/tuxguitar/app/transport/TGTransport.java
Fix for issue (or feature request) https://sourceforge.net/p/tuxguitar/feature-requests/101/
When playing and "pause" is clicked, move caret to currently playing position else, "pause" behaves exactly as "stop" (resetting caret to initial play position)
before:
https://github.com/helge17/tuxguitar/assets/129443524/c57b2770-2150-4963-979f-17c88be311c8
after:
https://github.com/helge17/tuxguitar/assets/129443524/8e0c434d-fa20-4cf8-bf33-455af7e5522e
Note: this is consistent with Android app behavior
=> pause Player instead of stop

TuxGuitar-ui-toolkit-jfx/src/org/herac/tuxguitar/ui/jfx/event/JFXZoomListenerManager.java, TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/event/SWTZoomListenerManager.java
Working on a compact laptop without mouse, the mouse wheel is emulated by 2-fingers movements on touchpad.
Basically the zoom in/out feature with Ctrl+touchpad was just unusable:
- start from 100% zoom level
- try to zoom-in slowly
- at some point it starts zooming-out so fast it finishes at 10%
Impossible to adjust precisely zoom level, except through many successive clicks in menu
Just understood why: keeping 2 fingers on the touchpad without moving generates mouse wheel events with value==0. It's a bit surprising, zero values make no sense: zero means no movement, so why trigger an event?
Logically, TuxGuitar was only expecting strictly positive or strictly negative values. And 0 was handled like -1
So, just stop moving or move too slowly, and it zooms-out continuously
Fix is trivial: …
=> fix annoying zoom issue with Ctrl+[2-fingers touchpad]

TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGNoteImpl.java
as requested in #61 
to avoid confusion with "forte"
=> display "1" instead of "f" for full tone bend

TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGDeleteNoteOrRestAction.java
Fix for issue #62
bug introduced when back-porting from 2.0beta fork the application of TGDeleteNoteOrRestAction action to current selection instead of current beat. This relies on 2 context attributes not defined in Android context (ATTRIBUTE_NOTE_RANGE, ATTRIBUTE_BEAT_RANGE)
Fix: if attributes do not exist or are empty, fallback to original implementation
To tests all branches of the successive if/else if/ conditions, trigger action:
- with nothing selected (to test on PC + Android)
- with a selection containing only notes for 1 voice
- with a selection containing notes for 2 voices
=> Fix for Android issue when deleting note

TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/duration/TGSetDurationAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGCleanBeatAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/installer/TGActionConfigMap.java, TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateModifiedDurationController.java
essentially backported from 2.0beta fork, but adapted to keep compatibility with Android version:
if the NOTE_RANGE and/or BEAT_RANGE attributes are not defined in action context or are empty,
then keep original implementation
Tested on Linux & Win10, JFX and SWT. This time I also tested the absence of regression in Android config (see #62)
=> apply actions to selection: set note duration, clean beat

TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGDecrementNoteSemitoneAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGIncrementNoteSemitoneAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGTransposeNoteSemitoneAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/undo/impl/custom/TGUndoableNoteRangeController.java, TuxGuitar/src/org/herac/tuxguitar/app/action/installer/TGActionConfigMap.java, TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateNoteRangeController.java
play sound if success and one single beat selected
tested on Linux & Win10, SWT & JFX:
- no click&drag selection: note under caret is transposed, beat is played
- after click&drag selection: everything selected is transposed, sound is played only if 1 single beat is selected
Also tested undo/redo
tested absence of regression on Android
=> apply actions to selection: increment/decrement semitone

TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/BeatMenuItem.java
enable menu items "Beat/semitone up" and "down" if at least one note is selected (#68)
even if the caret is not over a note
=> fix for #68

TuxGuitar-android/src/org/herac/tuxguitar/android/action/listener/cache/controller/TGUpdateShiftedNoteController.java, TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateShiftedNoteController.java
bug fix (#70): after shifting 1 note up or down, menuItems and toolBar icons "enabled" properties were not updated
e.g., after shifting 1 note up or down 1 string it was impossible to associate an effect to this note, or to shift it 1 string again
Fix in both PC and Android environments
=> update caret internal properties after shifting note 1 string

TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGChangeVelocityAction.java, TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java, TuxGuitar/src/org/herac/tuxguitar/app/action/installer/TGActionConfigMap.java, TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateModifiedVelocityController.java
continuing to apply actions to whole selection, this one is simple.
Inspired by 2.0beta fork, with following improvements:
- maintain compatibility with Android
- undo also works properly if selection covers several measures
=> apply "change velocity" action to selection

TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/duration/TGDecrementDurationAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/duration/TGIncrementDurationAction.java, TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoard.java, TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/matrix/TGMatrixEditor.java, TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/piano/TGPiano.java
see #73 
to be consistent with "+" and "-" default shortcuts: "increment duration" shall increment the duration from the user's point of view: less notes within 1 single measure
with this modification, Androip app behavior becomes consistent: arrow up increases note duration
also invert icons in FretBoard, MatrixEditor and Piano to keep actual behavior: arrow up increases note duration
=> invert Decrement/Increment Duration Actions

TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTable.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableBodyLayout.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableHeaderMeasures.java
fixes one issue when opening TG by opening a file with markers in it (e.g. file passed as an argument in command line, or double-clicking a file in graphical interface) . This could lead to draw a marker in a non-initialized track table, with SWT throwing an exception and crashing app
see #99 (2 independent problems mentioned in this issue)
Implementation of markers in track table was inspired by 2.0beta, but it was not expected that this drawing of markers could be called even before table is fully initialized.
Especially I did not think it was possible that `cellSize` would equal 0.0f, just a few lines after `int j = (int) Math.floor(scrollX / cellSize);`
I just discovered that dividing by 0.0f returns `NaN` and raises no exception.
=> check trackTable is initialized before drawing markers

TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Selector.java
Fix for #101
scenario (before the fix):
- open 2 songs
- in song 1, click in measure 4, without click&drag : no selection
- switch to song 2
- switch back to song 1 a selection appears in measure 4 where the cursor was
Explanation: introduced in 0d728c2ab26b2256e5ac00d7124182912bd3370f when fixing one bug backported from 2.0beta.
In 2.0beta, when user switches song, a selection is initialized where the cursor was.
BUT, since a selection of a single beat does not work, nothing happens
After the possibility to select 1 single beat selection was reintroduced, the consequences became visible
fix: when switching song, save/restore selection only if it's not empty
=> fix display of an erroneous selection when switching tabs

TuxGuitar-lib/src/org/herac/tuxguitar/document/TGDocumentContextAttributes.java, TuxGuitar/src/org/herac/tuxguitar/app/action/TGActionContextFactoryImpl.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGCopyAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGCutAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGRepeatAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/tablature/TGMouseClickAction.java
fix for #104
before the fix:
- activate score edition mode
- initiate selection with click&drag
- release mouse button in the score area if not on a note, it creates a note and clears selection (inconsistent) if on a note, it deletes note (inconsistent) and keeps selection
fixed: nothing is edited when selecting with click& drag in score edition mode
Also:
cleaner propagation of Selector.isActive through action context
=> fix selection in score edition mode

TuxGuitar-test/pom.xml, TuxGuitar-test/src/org/herac/tuxguitar/test/TGTest.java, TuxGuitar-test/src/org/herac/tuxguitar/test/TGTestSwitchTab.java, TuxGuitar/src/org/herac/tuxguitar/app/action/listener/save/TGUnsavedDocumentInterceptor.java
Objective of this pull request is to introduce the possibility to define test scenarios and run them automatically, to ease the development of new features and limit the risk of future regression.
Test module adds new external dependencies to Junit. However, **only the tests are dependent from this lib**, not the application itself. If for some reason this dependency becomes difficult to maintain some day, only the tests will be impacted.
Only a *very minor* modification has been implemented in the app source code: one string in `TGUnsavedDocumentInterceptor` class has been changed from `private` to `public`. This enables the test scenarios to bypass the confirmation popup when closing unsaved documents. This should be completely harmless, and have zero impact on the application or the …
=> first automated tests

TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP1InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP2InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP3InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP3OutputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP4InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP4OutputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5OutputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GTPOutputStream.java
Bugfix for Issue #109.
I have done this in a CSharp version long time ago. You should have a look if the Java syntax is correct.
GP1, GP2, GP3, GP4 are also affected.
=> KeySignature added

.gitignore
From what I read on the Internet it seems there is no consensus about which android studio files shall or shall not be in configuration.
I do not actively work on the Android version of TuxGuitar, just build and run it from time to time to check absence of regression. And each time Android Studio recreates these files that I delete manually after the test. Since none is actually present in configuration, it seems to me more logical to ignore them.
=> ignore android studio files

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/settings/items/SkinOption.java
an attempt to solve issue #119
objective is to avoid strings being truncated, when selecting first a skin with short info strings, then another one with longer strings
=> dynamically resize skin info labels

TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigDefaults.java, TuxGuitar/src/org/herac/tuxguitar/app/system/icons/TGSkinManager.java
see discussion in #119
user config file is kept when user upgrades TuxGuitar (starting from 1.6.0) If, in the newly installed version, user configured skin was deleted, then replace the configured value by (hardcoded) default.
Test done:
- start TuxGuitar and close it, to make sure config file exist
- edit config file (~/.config/tuxguitar/config/tuxguitar.cfg): replace value of parameter "skin" by an arbitrary value
- start TuxGuitar: user interface is displayed with Oxygen skin
- open "Tools/Settings/Skins" dialog: Oxygen is selected
- close TuxGuitar
- open config file: parameter "skin" is now set to "Oxygen"
=> prepare for future deletion of skins

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/matrix/TGMatrixEditor.java
See discussion in #131 
Before the fix:
- click in cell 1 in matrix editor: correct sound is played
- click in cell 2 corresponding to another instrument: instrument of click 1 is played
- click in cell 3 corresponding to another instrument: instrument of click 2 is played etc.
one member of TGChangeNoteAction context was not updated
=> fix sound mismatch in matrix editor

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/transport/TGTransportModeDialog.java
When something is selected with click & drag, loop range in transport mode dialog (F9) is correctly initialized with selection.
However, even when nothing was selected the values of loop range were updated
Scenario to reproduce bug:
- select measures 4 to 8 with click & drag
- type F9, loop range is initialized from 4 to 8 (OK)
- click 'training mode' then 'OK'
- click somewhere in measure 5 (empty selection)
- type F9: loop range is set from 5 to 5, even before clicking "OK" -> BUG
bug was introduced with 531495044d70a7e93afb29049527325cfbb7d8c4 (sorry for that!)
=> Fix bug when opening transport mode dialog

TuxGuitar-jack/src/org/herac/tuxguitar/jack/sequencer/JackMidiPlayerStarter.java, TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiPlayer.java, TuxGuitar-test/src/org/herac/tuxguitar/test/TGTest.java, TuxGuitar-test/src/org/herac/tuxguitar/test/TGTestPlayerPosition.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/measure/TGGoFirstMeasureAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/measure/TGGoLastMeasureAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/measure/TGGoNextMeasureAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/measure/TGGoPreviousMeasureAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/selector/TGExtendSelectionNextAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/transport/TGTransportPlayPauseAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/impl/transport/TGTransportPlayStopAction.java, TuxGuitar/src/org/herac/tuxguitar/app/transport/TGTransport.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Caret.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java, TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/transport/TGTransportModeDialog.java, TuxGuitar/src/org/herac/tuxguitar/app/view/toolbar/main/TGMainToolBarSectionTransport.java
Evolution is quite complex, so I would appreciate some complementary tests if possible.
I tried to limit the risk by implementing automated tests, but I would not be surprised if a few bugs remain.
Note: I could not fully test with Jack plugin enabled.
Where does the player start when hitting *play*? Where does the cursor go when hitting *pause* or *stop*?
Objective of this evolution is to rework how cursor and player interact, especially considering the "click & drag" feature introduced in 1.6.0. Examples of scenarios:
- select measures 4 to 6, type F9, click "play looped", click OK then *play*: it should loop from 4 to 6 (starts playing 6 before this evolution)
- after selecting something with click&drag, *play* should play once the selected area (plays from cursor to end of song before …
=> Rework of cursor position vs. player

TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
Value entered by user for transposition when importing a midi file was not considered to choose an appropriate tuning.
This could lead to negative fret numbers displayed in the tablature.
See #150
=> Fix midi import with transposition

TuxGuitar-ui-toolkit-jfx/pom.xml, TuxGuitar-ui-toolkit-jfx/src/org/herac/tuxguitar/ui/jfx/JFXFactory.java, TuxGuitar-ui-toolkit-jfx/src/org/herac/tuxguitar/ui/jfx/widget/JFXBrowser.java, TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/SWTFactory.java, TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/widget/SWTBrowser.java, TuxGuitar-ui-toolkit/src/org/herac/tuxguitar/ui/UIFactory.java, TuxGuitar-ui-toolkit/src/org/herac/tuxguitar/ui/widget/UIBrowser.java, TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/documentation/TGDocumentationDialog.java, build-scripts/tuxguitar-freebsd-jfx-x86_64/pom.xml, build-scripts/tuxguitar-linux-jfx-x86_64/pom.xml, build-scripts/tuxguitar-macosx-jfx-cocoa-x86_64/pom.xml, build-scripts/tuxguitar-windows-jfx-x86_64/pom.xml
to remove dependency to external web browser
Specific use case for Ubuntu, where distro's web browser cannot access local resources
see #153
Limitations:
- pom files updated for all configurations, but only tested with Linux/JFX, Linux/SWT, Win10/SWT
- no embedded controls for navigation (e.g. back, forward)
The method "openUrl" of application object is now unused, but I did not remove it: it can be used in future versions to link to an external website for online help
=> display doc in embedded browser

misc/build_tuxguitar_from_source.sh
see #159 (especially [freebsd/jfx issue](https://github.com/helge17/tuxguitar/pull/159#issuecomment-1826788310)), and #153
I could not run this exact build script in my environment, but I performed the same steps manually. Then, build of FreeBSD/JavaFX version succeeded.
So, I recommend to check before merging.
note: I could not either test if the produced app works correctly (I just configured build environment in freebsd, but no x server yet)
=> restore FreeBSD/JFX build

TuxGuitar/share/skins/Breeze-dark/skin.prop, TuxGuitar/share/skins/Breeze/skin.prop, TuxGuitar/share/skins/Oxygen/skin.prop, TuxGuitar/share/skins/Symbolic-dark/skin.prop, TuxGuitar/share/skins/Symbolic/skin.prop, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableCanvasPainter.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableColorModel.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableHeaderMeasures.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java
Objective: less aggressive for the eye
(graphically inspired by 2.0beta fork)
before:
after:
Implementation: a complete rework of color model (hopefully simplified). Colors are now indexed with named variables instead of integers. At least it clarifies which color goes where.
Configuration per skin is kept (more clear now), even if currently unused
=> rework of tracks table colors

TuxGuitar/share/help/about.html, TuxGuitar/share/help/detail_measure_beat.html
keeping the URLs as text, but removing  `<a>` tag
trade-off for security, now that doc is opened by embedded browser. A click on such a link and the embedded browser is in the wild, connected to Internet. If a vulnerability is discovered for embedded browser, it could have a severe impact on TuxGuitar's users, and most probably it would take a very long time before an eventual patch reaches all users of a TuxGuitar release. Since there is no control to enter a URL, this limits de facto the browser to the delivered files in local file-system, reducing the attack surface.
authors updated: that's for self-satisfaction ;)
=> remove links to external web pages from help, authors updated

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoard.java
fix for issue #196
bug introduced by ce35867c88b94c96024ea002c2b74e422efa67e9
surprisingly, initial implementation applied twice a (% 12) operation
=> fix issue when displaying scale

desktop/TuxGuitar-ui-toolkit-jfx/src/org/herac/tuxguitar/ui/jfx/widget/JFXAbstractScrollBar.java, desktop/TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/widget/SWTScrollBar.java, desktop/TuxGuitar-ui-toolkit/src/org/herac/tuxguitar/ui/widget/UIScrollBar.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java
to consider height of horizontal scrollbar
remove hard-coded value (effective height is platform-dependent)
removal of a limitation introduced by #176
=> adjust height of track table

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/matrix/TGMatrixEditor.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/track/TGTrackTuningChooserDialog.java
leading to app crash, but in very specific conditions
TGMatrixEditor:
- edit current track tuning, select one string with a VERY high value (>107)
- show matrix this tries to show name of a note >127, and fails with an exception
TGTrackTuningChooserDialog
- edit current track tuning
- edit tuning of one string, and in "Value" drop-down list select very first item "-- Select --" before C0 this fails to retrieve selected value (null pointer exception)
=> fix minor issues

common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
allocating notes on the lowest possible fret means on the highest possible string
so, notes should be allocated from highest to lowest to maximize chances to find a place for each note
see https://github.com/helge17/tuxguitar/issues/209#issuecomment-1902588352
=> fix midi import

desktop/TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/widget/SWTCheckBox.java, desktop/TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/widget/SWTControl.java, desktop/TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/widget/SWTRadioButton.java
See #52
in SWT configuration, with some versions of Linux/KDE, estimated width of checkboxes and radio buttons by SWT is underestimated
This results in truncated strings shown to user
This is NOT a fix, just a workaround.
To be removed one day when external issue is fixed
Consequence: some controls may have an extra (useless) margin of 10px on other platforms (Windows, mac, freebsd).
I tried to add a parameter, so that the workaround would only apply to Linux version, but this would have required to add some dependencies between modules in pom files, I think it's not worth it.
=> workaround for an external bug

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/measure/TGPasteMeasureAction.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGNote.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGPasteAction.java
See #218
this is NOT a fix
just a workaround, to avoid creating notes on non-existing strings when copy-pasting between different tracks
bug remains: what is finally pasted is a list of (string number, fret number)
so, if source and destination tracks don't have the same tuning, notes pitch change
Before this workaround:
- create a note on lowest string of a standard tuned guitar
- select beat, copy
- in a standard tuned bass track, paste: permanent error message
With this workaround, notes can be lost but app should no more crash
still some significant job TODO (see added comments)
no impact on android app
(only comments added in modules common to desktop/android)
=> workaround to avoid crash when pasting to track with less strings

desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateRemovedTrackController.java
fix #227
clear selection *after* removing track, in update controller, so before updating display (where the crash occurred)
It would have been cleaner to clear selection *before* removing track, ideally only if selection was active on the track to be removed
but TGRemoveTrackAction is in tuxguitar-editor-utils, where it cannot access Selector (in tuxguitar module), and cannot call Selector.clearSelection()
So this would require to reallocate all classes related to click&drag feature to different modules
(note: bug was back-ported from 2.0beta fork, together with click&drag feature)
=> avoid a crash when deleting track with an active selection

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/measure/TGPasteMeasureAction.java, common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/clipboard/TGClipboard.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/TGSongSegment.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/TGSongSegmentHelper.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/TGStoredBeatList.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/TGTrackSegment.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGTrackManager.java, common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java, desktop/TuxGuitar-test/src/org/herac/tuxguitar/test/TGTestAllocateNotesToStrings.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGCopyAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGPasteAction.java
Complete rework of copy-paste feature, with the objective to keep *notes* unchanged when source and destination tracks don't have the same tuning. Previous implementation pasted *fret numbers*, this broke the global harmony.
Also: forbid copy/paste from percussion track(s) to non-percussion track(s) and vice-versa. Previously this led to weird results.
See #218 
Allocation is done beat per beat.
Strategy:
1. When source and destination tracks have the same tuning, keep notes and fingering unchanged, just as before
else:
2. try to move all notes to the closest string in destination tuning. "Closest" in terms of string pitch, not string number (number of strings may change)
example of use cases:
- copy from one standard tuned guitar to a guitar with F tuning: keep "fingering patterns" …
=> copy-paste: adapation to different tuning presets

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiRepeatController.java
fix #234
scenario: define loop over an interval corresponding to an alternative repeat >1, hit play
before this fix, player never starts
=> fix play loop in alt repeat

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGMeasureImpl.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTimeSignature.java
this is a trade-off
restoring vertical alignment of beats in multitrack mode when bends are present is complex. And this should lead to a significant waste of space So, this alignment is not strictly respected, especially when many wide bend movements are displayed in one track and none in the other(s). Max width of bend movements of all tracks is "distributed" linearly in each measure of each track.
At least, available horizontal space is used in a more optimal way.
see #242
=> bend and multitrack: better horizontal spacing

desktop/TuxGuitar/dist/tuxguitar-shortcuts.xml, desktop/TuxGuitar/share/lang/messages.properties, desktop/TuxGuitar/share/lang/messages_bg.properties, desktop/TuxGuitar/share/lang/messages_ca.properties, desktop/TuxGuitar/share/lang/messages_cs.properties, desktop/TuxGuitar/share/lang/messages_de.properties, desktop/TuxGuitar/share/lang/messages_el.properties, desktop/TuxGuitar/share/lang/messages_es.properties, desktop/TuxGuitar/share/lang/messages_eu.properties, desktop/TuxGuitar/share/lang/messages_fi.properties, desktop/TuxGuitar/share/lang/messages_fr.properties, desktop/TuxGuitar/share/lang/messages_hu.properties, desktop/TuxGuitar/share/lang/messages_it.properties, desktop/TuxGuitar/share/lang/messages_ja.properties, desktop/TuxGuitar/share/lang/messages_ko.properties, desktop/TuxGuitar/share/lang/messages_lt.properties, desktop/TuxGuitar/share/lang/messages_nl.properties, desktop/TuxGuitar/share/lang/messages_pl.properties, desktop/TuxGuitar/share/lang/messages_pt.properties, desktop/TuxGuitar/share/lang/messages_ru.properties, desktop/TuxGuitar/share/lang/messages_sr.properties, desktop/TuxGuitar/share/lang/messages_sv.properties, desktop/TuxGuitar/share/lang/messages_uk.properties, desktop/TuxGuitar/share/lang/messages_vi.properties, desktop/TuxGuitar/share/lang/messages_zh.properties, desktop/TuxGuitar/share/lang/messages_zh_GB.properties, desktop/TuxGuitar/share/lang/messages_zh_TW.properties, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/EditMenuItem.java
See #220 
added menu items: to make actions visible to user
Ctrl+A is a usual shortcut for "select all" action in many applications
=> added selection-related menu items, reallocate Ctrl+a shortcut

desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLSongWriter.java, desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
See #169
- addition of DOCTYPE to create explicit link with dtd
- addition of explicit version 4.0
- reordering of xml nodes
- adaptation of tempo definition
- explicit -1 octave offset for G clef As a guitar-oriented software, TuxGuitar always applies this convention internally, even if not drawn on the score
- most critical modification: export both score and tablature with adequate attributes. Previously these attributes were mixed. E.g. one guitar track was exported as a 6-line score (!) now it is exported as a 5-line score plus a 6-line tab
- deletion of optional xml nodes with low added value
- addition of TuxGuitar version in <encoding><software> node
- redefined file extension to ".musicxml"
source MusicXML specification:
https://www.musicxml.com/for-developers/
Notes:
- to …
=> export to MusicXML 4.0

README.md, desktop/TuxGuitar/dist/about_description.dist
@helge17: I will not merge this PR myself, I would like you to review it first.
My objective is mainly to ease access to "contribute.md" from repo's main page (link was deleted at my request, because of markdown syntax appearing in help/about dialog: 566b3c5b5ae5a1de4430e20b477dc3746d9fad00)
Not very comfortable to split "README" in 2, especially for future maintenance. Not ideal also to embed in deskop app an absolute link to "contribute.md".
Don't hesitate to reject PR if you can think of a better solution.
=> split README in 2 independent files

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGSetNoteFretNumberAction.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/TGSongSegmentHelper.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGTrackManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTrack.java, common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGPasteAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/edit/EditorKit.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/grace/TGGraceDialog.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/matrix/TGMatrixEditor.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/trill/TGTrillDialog.java
See #256
objective: 1 single hardcoded constant for max fret number
implementation:
- constant stored in TGTrack, so it can be customized per track one day
- removed many occurrences of hardcoded limits, use value from TGTrack
difficult to know if other occurrences still remain, that's possible
- addition of a limit to grace note effect
=> rationalize definition of maximum fret number

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/print/TGPrintLayout.java, desktop/TuxGuitar/share/lang/messages.properties, desktop/TuxGuitar/share/lang/messages_bg.properties, desktop/TuxGuitar/share/lang/messages_ca.properties, desktop/TuxGuitar/share/lang/messages_cs.properties, desktop/TuxGuitar/share/lang/messages_de.properties, desktop/TuxGuitar/share/lang/messages_el.properties, desktop/TuxGuitar/share/lang/messages_es.properties, desktop/TuxGuitar/share/lang/messages_eu.properties, desktop/TuxGuitar/share/lang/messages_fi.properties, desktop/TuxGuitar/share/lang/messages_fr.properties, desktop/TuxGuitar/share/lang/messages_hu.properties, desktop/TuxGuitar/share/lang/messages_it.properties, desktop/TuxGuitar/share/lang/messages_ja.properties, desktop/TuxGuitar/share/lang/messages_ko.properties, desktop/TuxGuitar/share/lang/messages_lt.properties, desktop/TuxGuitar/share/lang/messages_nl.properties, desktop/TuxGuitar/share/lang/messages_pl.properties, desktop/TuxGuitar/share/lang/messages_pt.properties, desktop/TuxGuitar/share/lang/messages_ru.properties, desktop/TuxGuitar/share/lang/messages_sr.properties, desktop/TuxGuitar/share/lang/messages_sv.properties, desktop/TuxGuitar/share/lang/messages_uk.properties, desktop/TuxGuitar/share/lang/messages_vi.properties, desktop/TuxGuitar/share/lang/messages_zh.properties, desktop/TuxGuitar/share/lang/messages_zh_GB.properties, desktop/TuxGuitar/share/lang/messages_zh_TW.properties, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/printer/TGPrintSettingsDialog.java
main objective: enable pdf export/print of detailed bends representation
default remains "compact mode = true", to save paper
see #202
=> enable pdf export and print NOT in compact mode

desktop/build-scripts/tuxguitar-freebsd-jfx-x86_64/pom.xml, desktop/build-scripts/tuxguitar-freebsd-swt-x86_64/pom.xml, desktop/build-scripts/tuxguitar-linux-jfx-x86_64/pom.xml, desktop/build-scripts/tuxguitar-linux-swt-x86_64/pom.xml, desktop/build-scripts/tuxguitar-macosx-jfx-cocoa-x86_64/pom.xml, desktop/build-scripts/tuxguitar-macosx-swt-cocoa-x86_64/pom.xml, desktop/build-scripts/tuxguitar-windows-jfx-x86_64/pom.xml, desktop/build-scripts/tuxguitar-windows-swt-x86_64/pom.xml, desktop/pom.xml
see #283
following 2f681c7d5c82509fbf6d1ef573ed505070e905ab
commons-compress update now requires explicit dependency to commons-io
needed to open .gp files
tested on Linux (openSUSE Tumbleweed) and Windows 10, SWT and JFX
tested on FreeBSD, SWT only
built but not tested on FreeBSD, JFX
not built not tested on macOS
@helge17 : since it modifies the pom files, I would appreciate if you could test in macOS configuration (I prefer not to merge this PR myself)
=> fix dependency

desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLLyricWriter.java, desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
Adds basic musicxml lyric support
my notes on the state machine:
[Quick sheets.pdf](https://github.com/helge17/tuxguitar/files/14605513/Quick.sheets.pdf)
Not sure about the naming of my methods and classes.
Now it will export the lyrics twice, to the main track and to the tablature. Not sure about this, maybe only on the main track is better.
In the `getLyricSlice` function I'm using `Arrays.stream`,  the are other ways to do this if this is only supported in newer Java versions.
I did add javadoc compatible comments. I let it generate in `doc/java_docs` but the config for this is not in this request.
Take your time with the review. Java is a language I didn't touch in a decade, so there are probably better ways to do some things.
Cheers,
Menno
=> Adds basic musicxml lyric support

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTable.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableDividerHelper.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableDividerListener.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java
#330 bug fix, this column's width could only be reduced, not increased. Bug was introduced with 2cfb9c919119eedece46eb52d656c88000b4af66
New format of track table was (partially) back-ported from TuxGuitar2.0beta fork
Modification of TGTableDividerListener was forgotten
=> make "instrument" column resizable in track table

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiSequenceParser.java
=> Correctly export percussion tracks when using `Export Audio File`

common/TuxGuitar-lib/src/org/herac/tuxguitar/ui/resource/UIPainter.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/util/configuration/TGConfigManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigDefaults.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigKeys.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Caret.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Tablature.java
Make caret more visible, and change configuration parameters so modification is effective also for users upgrading TuxGuitar version.
@helge17 I would appreciate if you can review:
- the graphical rendering (always subjective)
- could you please check if this is OK also in macOS configuration?
- I would appreciate your opinion about how to depreciate configuration parameters. Since configuration folder is preserved when TuxGuitar is updated, we had already added the possibility to create new parameters in new version. This case, I would like to replace old configuration parameters with new ones. So I have created a list of "obsolete key names", and updated the configuration managers to delete these old parameters. Does it seem reasonable to you?
=> make caret more visible

desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigDefaults.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigKeys.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigManager.java
yet unused: no functional consequence, for future use
targeted use case: to handle smooth transitions between app versions when user upgrades/downgrades app
example: would have been useful for 3190ae77b9ff3f186cbfc76a0bbdf7fe615f58b4 to adapt default behavior when user upgrades from an old version
=> add app version in user config file

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGBeatImpl.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/settings/items/StylesOption.java
2 fixes: 
- size of rectangle around played beat: consider lowest note when tablature is not displayed
- restore background color to default when "Default" button of "Tools/Settings" dialog is clicked
=> highlight playing measure (fix)

common/TuxGuitar-gpx/src/org/herac/tuxguitar/io/gpx/GPXDocumentReader.java
Recently I've found some `.gp` files which work fine in GuitarPro but don't in TuxGuitar. Instruments of all tracks were replaced by one of the first track.
I've discovered that they are in GP7 format without specified general midi channels at `MidiConnection` element in `score.gpif` file in them. 
In that case TuxGuitar reads default value `0` as midi channels. The same midi channel in all tracks causes all channels but the first one skip their initialization.
I made sure that the default channel value was one that had not yet been used.
=> Separated default gmChannels for gpx

common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiFileReader.java
This PR fixes a typo in an error message (`exactely` -> `exactly`).
It also fixes a couple of minor whitespace issues.
=> Fix typo in MidiFileReader.java

desktop/TuxGuitar-synth-export/src/org/herac/tuxguitar/io/synth/TGSynthSongWriter.java
computation of audio file duration was erroneous
when too high, this had no audible consequence
when too low, output file was truncated
see #431
=> fix audio export

desktop/TuxGuitar-synth-export/src/org/herac/tuxguitar/io/synth/TGSynthSongWriter.java
correction of 1e2268d5092dc247b72c9d9ce0b7621e113a5cfe
forgot a factor 2 in duration computation (nb of channels)
see #431
=> fix audio export duration

common/TuxGuitar-lib/src/org/herac/tuxguitar/io/base/TGFileFormatManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/file/TGWriteFileAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateSavedSongController.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateWrittenFileController.java
see #462
use case:
- open myFile.tg file
- "File/Export" (e.g. pdf, lilypond, musicxml or whatever) this exports correctly myFile.xxx, but current active document now remains myFile.tg
also don't change attribute "unsaved"
File/Save (or Save As) correctly updates doc uri and unsaved attributes
=> don't change current doc uri when exporting song

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/measure/TGMeasureCleanDialog.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/measure/TGMeasurePasteDialog.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/measure/TGMeasureRemoveDialog.java
This fix added a missing colon after "Paste Count" in the menu: Measure -> Paste Measure, like in the menu: Measure -> Add Measure -> "Add Count:".
Greetings,
Gootector
=> Missing colons in the Measure menu

common/TuxGuitar-lib/src/org/herac/tuxguitar/io/base/TGFileFormatManager.java, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/TESongReaderPlugin.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/file/TGWriteFileAction.java
see [this comment](https://github.com/helge17/tuxguitar/pull/481#issuecomment-2262278439) in PR481
This PR moves ".tef" files from File/Import to File/Open menu. I am clearly hesitating for midi files.
Looking at all file formats TuxGuitar can read: TablEdit, PowerTab, GuitarPro and TuxGuitar all produce *tablature* files. Basically, the same *nature* of data encoded differently. For these, I think File/Open makes sense.
Midi files contain data of a fundamentally different *nature*. The imported data is significantly transformed when TG opens a midi file. So I think it makes sense to keep it in File/Import menu. It makes more clear to users the data is "imported", hence "modified".
By the way, I have to fix something: following 340f89993c8a9206ff4030c87ed4fc37d1faefa3, old TG file formats …
=> move ".tef" from File/Import to File/Open

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoard.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoardConfig.java
for better readability, see #461
- display notes names in circles instead of rectangles
- use configured colors (note & scale) for background
- foreground color is black or white, depending from background brightness
As usual when it comes to user interface, I would appreciate some feedback before merging, see screenshots in #461
=> graphical rework: display note names and scales on fretboard

common/TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP3OutputStream.java, common/TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP4OutputStream.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/io/tg/TGSongReaderImpl.java
for better code readability
see 372283d391bf910e9ac04120a94ea9744108b6e8
=> Re-introduce TGDivisionType.NORMAL as an alias for DIVISION_TYPES[0]

common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/io/tg/TGSongWriterImpl.java
revert one modification done in 27502a6ecd264637887ecc4df20ea0ab89dbea0e
no more needed after android dependencies update
=> fix a warning

common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/io/tg/TGStream.java
modification was introduced to bypass an Android build issue no more needed after android dependencies update
see discussion in 462f2224401f7eedb5e23bac1fef1526af234080
=> revert 27502a6ecd264637887ecc4df20ea0ab89dbea0e (continued)

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TGControl.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Tablature.java
this one was pretty tricky (#534)
(bug present since at least TG 1.5.6, not tested before)
test scenario to reproduce issue:
- multitrack song, edition mode active
- click in track1
- scroll down several tracks with scrollbar, until caret is no more visible
- move mouse into tab => this scrolls back to track1 unexpectedly
root cause:
TGMouseMoveAction and/or TGMouseExitAction are triggered at end of test scenario (because edition mode active).
After action is processed, TGUpdateListener.processPostExecution is called, this triggers an update of cached buffer: TGUpdateBuffer.apply, then it calls TGUpdateBuffer.applyUpdateMeasures
at this stage, the list of measures to update is empty, because it was cleared by TGUpdateListener.processPreExecution, and no measure changed since.
This ends up …
=> fix one scrolling issue

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/event/TGUpdateMeasuresEvent.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/tablature/TGMouseExitAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/tablature/TGMouseMoveAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TGControl.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Tablature.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TablatureEditor.java
see:
- original issue: https://github.com/helge17/tuxguitar/issues/534
- db7b368f5577118e35007045946d6a5bccffbd26 first attempt to fix (KO)
- unexpected side effect: https://github.com/helge17/tuxguitar/issues/536
Detailed description of sequence leading to bug is available in commit db7b368f5577118e35007045946d6a5bccffbd26
Another attempt to fix, limiting the risk of side effect: Behavior of Tablature.updateMeasures is modified only after processing TGMouseMoveAction or TGMouseExitAction
=> fix one scrolling issue (again)

common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/TGStoredBeatList.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGTrackManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGBeat.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGPasteAction.java
see #545
preceding implementation of "paste selection" was imported from 2.0beta fork, and was too simplistic:
- remove beats from song
- insert beats to paste
Several issues:
- did not consider multiple voices, this led to invalid measures in some cases
- when removing beats, everything is shifted left, this can modify following measures in the whole song, typically splitting long notes in 2 (over measures boundaries)
quite painful: damaged measures may be very far, even off-screen, so the consequence of this bug may be seen a long time after it occurred
Note that this new implementation is much more complex
Some bugs in corner cases are still possible. Anyway it this occurs it should be local
=> fix paste selection issue

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGLayout.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TGControl.java
To sum up, in SWT configuration:
- on Linux, scrollbars are semi-transparent, overlap the canvas content, and appear/disappear dynamically
- on Windows, scrollbars are solid and occupy a fixed area in canvas
Dynamic appearance/disappearance of tablature scrollbars created a serious performance issue on Linux following an SWT update. It was fixed by hiding scrollbars when playing (20ae8bee2671e52678c0372bc076487eb4b3f95f).
This fix created another issue on Windows: when player starts or stops, hiding/showing scrollbars changes the size of the available area to paint tablature. This provokes an update of layout, moving measures around in some cases.
This commit targets a solution compatible with both OSes:
- restore scrollbar(s) when playing, to fix Windows issue
- aggressive performance …
=> Restore scrollbars when playing, performance optimization

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TGControl.java
- when zooming in/out (#568)
- when changing track (click in track table)
This restores part of behavior implemented before first perf optimization (20ae8bee2671e52678c0372bc076487eb4b3f95f): in some cases, tablature is redrawn twice (only when not playing).
Because dimensions are re-computed when redrawing. In some cases, after redrawing tab shall scroll to display caret. So it needs to be redrawn. This could be probably optimized, by separating computation from effective display.
=> fixed scrolling issues (again)

.github/workflows/macos-maven.yml
The macOS-12 environment is deprecated at github
=> update MacOS workflow

desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/TEInputStream.java, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/TESongParser.java, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/TESongReader.java, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/base/TEComponentEnding.java, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/base/TEComponentTempoChange.java
Adds support for tempo changes, alternative endings, and repeats components in the TEF v2 import process.
This PR re-uses implementation done initially in PR #600
(splitting tef v2 and tef v3 into different PRs)
=> Add tempo change / ending / repeat TEF v2 support

common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/song/models/TGScale.java, common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/util/TGMusicKeyUtils.java, common/TuxGuitar-lib/src/test/java/org/herac/tuxguitar/util/TestMusicKeyUtils.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/tools/scale/ScaleManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoard.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/piano/TGPiano.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/scale/TGScaleDialog.java
fixes #204, at least partially: scales with flat base notes can be displayed, and result should be ok for many common scales.
Not a perfect solution though. It can't be correct in all cases, as there are no double-sharp / double-flat concepts in TuxGuitar currently. E.g. D# major scale is displayed with 3 sharps (in an incorrect order) instead of 5 sharps + 2 double-sharps.
Intentionally, E#, Fb, B# and Cb scales are not accessible.
=> fix for scales notes display on fretboard

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/print/TGPrintLayout.java
Addressing #609 
Add song details such as song name, artist, author, album, release year, transcriber, tab creator to the top of exported file.
For SVG export, to maintain consistency with PDF printing (where paintHeader() exists in TGPrintLayout), we could implement paintHeader() within TGLayoutVertical. However, this would directly impact the main program by displaying song details on top of the tab.
Alternatively, we can create a new subclass of TGLayout (called TGSvgLayout for example). This subclass would largely mirror TGLayoutVertical but include the necessary paintHeader() implementation specifically for SVG export, minimizing unintended side effects on the main program.
=> Add song details to exported PDF & SVG file

desktop/TuxGuitar-tef/share/META-INF/services/org.herac.tuxguitar.util.plugin.TGPlugin, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef3/TESongReader.java
see #636
tef v3 files are recognized by file content.
tef v2 files are recognized by file extension "tef".
As file readers for tef v2 AND v3 are associated to the same "tef" extension, it is important that tef v2 plugin is registered BEFORE tef v3
See explicit comment added in services file
=> associate "tef" file format to tef v3

desktop/TuxGuitar-svg/src/org/herac/tuxguitar/io/svg/SVGController.java, desktop/TuxGuitar-svg/src/org/herac/tuxguitar/io/svg/SVGPainter.java
I have to use attribute `text-anchor` on svg file in order to make the text aligned correctly. The old way of calculating X-coordinate to paintString() doesn't work.
=> Add more song details to exported SVG file

common/TuxGuitar-ascii/src/org/herac/tuxguitar/io/ascii/ASCIIOutputStream.java, common/TuxGuitar-ascii/src/org/herac/tuxguitar/io/ascii/ASCIITabOutputStream.java
I extended the tuxguitar ascii export.
The ascii export includes now the additional note effects
- hammer on
- pull off
- slide up
- slide down
- bend up
- release bend
The note effect for dead notes was already included.
The notation is according to [ASCII Tab](https://en.wikipedia.org/wiki/ASCII_tab).
| Symbol | Technique      |
|--------|----------------|
| h      | hammer on      |
| p      | pull off       |
| b      | bend string up |
| r      | release bend   |
| /      | slide up       |
| \      | slide down     |
| X      | dead note      |
The test environment was
- Ubuntu 24.04.1 LTS
- eclipse-java-2023-12-R-linux-gtk-x86_64
The attached `ascii-effects.tg` file demonstrates the export, see [ascii-effects.zip](https://github.com/user-attachments/files/18640555/ascii-effects.zip) …
=> add note effects to ascii export

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGDeleteNoteOrRestAction.java, common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/song/managers/TGMeasureManager.java, common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/song/models/TGBeat.java
see #579
TGBeat: forgot to update one test after .preciseStart defaults to null
TGMeasureManager.moveBeat: avoid concurrent modification of beats
precise start, was throwing an exception with copy/paste measure action
TGMeasureManager.removeVoice: need to refresh beats preciseStart if action
is done in free edition mode
TGDeleteNoteOrRestAction/TGMeasureManager.removeVoiceWithoutControl:
specific behavior of free edition mode when deleting a rest
=> bug fixes, free edition mode

common/TuxGuitar-ascii/src/app/tuxguitar/io/ascii/ASCIIOutputStream.java, common/TuxGuitar-ascii/src/app/tuxguitar/io/ascii/ASCIITabOutputStream.java
I further extended the tuxguitar ascii export.
The ascii export includes now chord names.
The attached file [ascii-chords.zip](https://github.com/user-attachments/files/19244555/ascii-chords.zip) demonstrates the export.
The implementation has the side effect, that for multiline tabs there is an additional empty line between tabs if there are no chords at all.
The test environment was
- Ubuntu 24.04.2 LTS
- eclipse-java-2023-12-R-linux-gtk-x86_64
```console
Cmaj7   Ebm6add9/5- \Gb D#m C7sus2
E|-12----|-13-------------------------|
B|-12----|-13------------------11-----|
G|-12----|-14--------------11--15-----|
D|-14----|-13--------------8---12-----|
A|-15----|-15--------------9---15-----|
E|-------|-14--------------11---------|
```
=> add chords to ascii export

desktop/TuxGuitar/src/app/tuxguitar/app/action/installer/TGActionConfigMap.java, desktop/TuxGuitar/src/app/tuxguitar/app/action/listener/cache/controller/TGUpdateReadSongController.java
this could happen with foreign format songs (e.g. guitar pro), or songs produced by older versions of TuxGuitar
see #579
=> open Measure Errors dialog when an invalid song is opened

common/TuxGuitar-gpx/src/app/tuxguitar/io/gpx/GPXDocumentParser.java, common/TuxGuitar-gpx/src/app/tuxguitar/io/gpx/GPXDocumentReader.java, common/TuxGuitar-gpx/src/app/tuxguitar/io/gpx/score/GPXBeat.java
This should address #680 
GP8:
Tux:
GP project upload: 
[GP_Project.zip](https://github.com/user-attachments/files/19324731/GP_Project.zip) | Github won't let me upload the .gp file so it's in the zip.
Unfortunately I didn't find a better way at handling this, but if you have any suggestions please let me know. GPX has the grace notes on a separate beat from the notes they are linked to, so we need to parse the grace note beat, then the real beat after and reconnect the grace notes.
Additionally GP7/8 support multiple back-to-back beats of grace notes, which I don't believe would work in TuxGuitar as grace notes are effects on regular TGNotes, and can only have 1 grace note effect. In that case, I count every second grace note beat as a real note. Here's a view in GP and then Tux, where …
=> Add GPX grace note support

desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java
This PR brings
- writes the optional capo element only when needed
- marks the tab staff as "alternate"
- adds support for let-ring elements
- marks tab notes as stemless
- minor formatting
NB: LetRing is exported as hanging tie. If this should be the "L.R." text, it has to be exported as such.
=> Improve MusicXML export

AUTHORS, desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java, desktop/TuxGuitar/share/help/about.html
This adds export of the correct notehead for dead notes (in standard notation) and the palm mute symbol. 
Furthermore it makes the number of staves and the absence of a part symbol explicit.
=> [MusicXML] export dead note

common/TuxGuitar-lib/src/main/java/app/tuxguitar/graphics/control/TGNoteImpl.java
when one note in beat n is tied and beat n-1 is a rest, then the player does not consider note is tied to any note in beat n-2 graphically, a tie to beat n-2 was drawn
now, graphical representation is consistent with player behavior
see #698
=> don't link tied note to a rest graphically

.gitignore, INSTALL.md
Install instruction modification to download correct file for SWT.
On my M3 MacBook, following INSTALL.md with the proposed modification, I succesfully build TuxGuitar. Using openjdk from homebrew it starts well and run perfectly :)
=> Update MacOS aarch64 (Mac Mx) build instruction

desktop/TuxGuitar/src/app/tuxguitar/app/action/installer/TGActionConfigMap.java
action does not make sense unless a specific error is selected in dedicated dialog
(avoid null pointer exception)
see #723
=> disable shortcut for "fix measure" action

.github/workflows/macos-maven.yml
Add support to Mac workflow to support aarch64.
Generated package test on my M3 Mac. Adding into JRE from brew openjdk works well:
$ cp -R /opt/homebrew/opt/openjdk/ Contents/MacOS/jre
Warning, launching the .app directly does not work (it ask for rosetta) but in cmd line ./tuxguitar.sh start perfectly.
I will look for the previous warning, but I prefer to publish now as it can help other searching for an aarch64 version.
=> Update Mac Workflow for aarch64

desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/errors/TGMeasureErrorDialog.java
when clicking in first item of measure error dialog, if caret is in a valid measure
see #723
=> fix null pointer exception

desktop/TuxGuitar/src/app/tuxguitar/app/view/component/tab/Selector.java
to reproduce bug:
- create a way too long measure in free edition mode
- select with click & drag from right to left, starting in the measure following the invalid one
Selection needs the beats to be ordered correctly according to their .start attribute. This is not always the case when a measure is too long
fix #733
=> fix crash when selecting an invalid measure

common/TuxGuitar-editor-utils/src/app/tuxguitar/editor/action/note/TGInsertRestBeatAction.java, common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/managers/TGMeasureManager.java, common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/managers/TGTrackManager.java
fix #736 
continuation of beat start rework, introduced to fix tuplets duration issue.
Propagation of TGBeat.preciseStart, and removal of calls to now deprecated TGBeat.setStart method
=> Fix delete rest

desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java
As dynamics are not "real dynamics" (see #588), they should not be exported as such. Especially because every velocity is written before every note, which doesn't make any sense within chords, and results in all dynamic symbols put on top of each other:
This changes the exporter to write the velocity for every note instead of writing dynamic symols.
NB: I left the function for writing dynamics there for the case #588 will be addressed.
=> [MusicXML] export velocity instead of visual dynamics

desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java
Export up strokes and down strokes to MusicXML. (In chords it is only applied to the first note.)
=> [MusicXML] export pick stroke

desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java
This PR adds the `beats` attribute to trills in the MusicXML export.
=> Export trill beats

desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java
First attempt to improve the output of metadata in MusicXML export:
- composer is only written, if it is not empty
- copyright information is exported
- current data is written
=> [MusicXML] extend metadata

.github/workflows/android-gradle.yml
apk is useless, as not signed
without this, the test is sufficient to check Android app builds correctly
=> android workflow: remove apk

desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java
This brings fixes to the export of clefs in MusicXML:
- C clefs are now correctly exported, but for now with `clef-octave-change` (see #701)
- clef changes are marked to be `after-barline` like they appear in TuxGuitar
- TAB clef is only written at the beginning
=> [MusicXML] fix clef export

common/TuxGuitar-editor-utils/src/main/java/app/tuxguitar/editor/action/note/TGDeleteNoteOrRestAction.java, common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/managers/TGMeasureManager.java
@helge17: some testing would be appreciated if you can. I hope this should simplify the management of multi-voices in free edition mode.
Basically, the idea is to prefer "holes" in a voice than overlaps. These are easier to fix, as TG tries to fill them automatically with rests, and succeeds most of the times.
With this, your test file used in #760 should look very different. Here is an illustration of the difference before/after this PR.
In this test, one note duration is increased, first in normal mode, then in freeEditionMode. Before the PR, this creates an overlap with following beat (00:09 in video). After the PR, this inserts a rest in the other voice (00:25). That should be more understandable, and easier to fix.
https://github.com/user-attachments/assets/9d320ee8-c93e-4c9f-af53-780 …
=> Free edition mode, simplify multi-voices

desktop/TuxGuitar/src/app/tuxguitar/app/action/impl/selector/TGUpdateDragSelectionAction.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/component/tab/edit/EditorKit.java
don't consider active voice when selecting with click & drag
visually, user sees a selection of *beats*, independently from voices
see #767
=> fix selection issue

desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/toolbar/TGMainToolBarDialog.java
JFX generates events differently from SWT
need to wait all objects to be initialized before enabling event listeners on drop-down lists
Or else it throws exceptions when opening dialog
=> fix mainToolBar (JFX)

desktop/TuxGuitar/src/app/tuxguitar/app/system/icons/TGIconManager.java
this icon does not make sense in the table
66aa31172a55794d92ccd76939adcd746c4ed38d was done a little too fast...
=> minor refactoring

desktop/TuxGuitar-AudioUnit/jni/app_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI.cpp, desktop/TuxGuitar-AudioUnit/jni/app_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI.h, desktop/TuxGuitar-AudioUnit/pom.xml, desktop/TuxGuitar-AudioUnit/share/META-INF/services/app.tuxguitar.util.plugin.TGPlugin, desktop/TuxGuitar-AudioUnit/share/lang/messages.properties, desktop/TuxGuitar-AudioUnit/share/lang/messages_de.properties, desktop/TuxGuitar-AudioUnit/share/lang/messages_fr.properties, desktop/TuxGuitar-AudioUnit/share/lang/messages_it.properties, desktop/TuxGuitar-AudioUnit/share/lang/messages_ja.properties, desktop/TuxGuitar-AudioUnit/share/lang/messages_sv.properties, desktop/TuxGuitar-AudioUnit/src/app/tuxguitar/player/impl/midiport/audiounit/MidiPortReaderAudioUnit.java, desktop/TuxGuitar-AudioUnit/src/app/tuxguitar/player/impl/midiport/audiounit/MidiPortReaderPlugin.java, desktop/TuxGuitar-AudioUnit/src/app/tuxguitar/player/impl/midiport/audiounit/MidiReceiverImpl.java, desktop/TuxGuitar-AudioUnit/src/app/tuxguitar/player/impl/midiport/audiounit/MidiReceiverJNI.java, desktop/TuxGuitar-AudioUnit/src/app/tuxguitar/player/impl/midiport/audiounit/settings/MidiSettingsHandler.java, desktop/TuxGuitar-AudioUnit/src/app/tuxguitar/player/impl/midiport/audiounit/settings/MidiSettingsPlugin.java, desktop/TuxGuitar-AudioUnit/src/app/tuxguitar/player/impl/midiport/audiounit/utils/MidiConfigUtils.java
AudioUnit support SF2 sound bank, this commit allow customization of it with tuxguitar-synth-audiounit.soundbank.path variable from tuxguitar-synth-audiounit.cfg configuration file.
In addition, small "bugfix" to call send NoteOff MIDI event during noteOff call.
=> [macos][audiounit] Allow customization of the soundbank

common/TuxGuitar-editor-utils/src/main/java/app/tuxguitar/editor/action/track/TGSetTrackInfoAction.java
don't consider max fret number for percussion track, or most of its content is deleted when track is renamed
fix for issue #829
=> fix issue when renaming percussion track

common/TuxGuitar-lib/src/main/java/app/tuxguitar/player/base/MidiPlayer.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/toolbar/main/TGMainToolBarItemTimeCounter.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/toolbar/main/TGMainToolBarSectionTempo.java
see #842
to reproduce issue:
- open default template
- double-click on track to show track properties dialog
- in "Instrument" drop-down list, click "-- Select --'
- click on "Close" button
- click on "play" button in toolbar
=> fix issues when no instrument selected

common/resources/lang/messages.properties, common/resources/lang/messages_es.properties, desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/settings/items/MainOption.java
I have made a GUI for play-when-moving, in case you want to add this feature to the official version.
I have added English and Spanish (because Spanish is my native language). I could try to translate the other languages using Artificial Intelligence, although I assume you already have a better way to do it.
Hope it helps.
=> GUI for play-when-move with two languages

common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/managers/TGSongManager.java
fix #863
bug scenario (before this fix):
- put caret on last beat of song
- add line break to current measure
- move right with keyboard
this creates a new measure (ok), but with a line break (KO)
=> no line break for new measures

docs/CONTRIBUTING.md
GitHub displays CONTRIBUTING.md file when browsing docs/ folder AND home page,
so relative links cannot work: replace by absolute links
problem: some links in this doc will only be correct after merging in master
=> docs: fix links
