TuxGuitar-android/src/org/herac/tuxguitar/android/properties/TGPropertiesImpl.java
forgotten in f6ea4a599af97f6abe67efaabbd49123ee3a1f80
sorry for that
=> Fix: ensuring future compatibility with older versions (Android)

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/transport/TGTransportModeDialog.java
Proposal to implement relevant [feature request](https://sourceforge.net/p/tuxguitar/feature-requests/100/) from SourceForge
replace drop-down list by spinner to select play tempo
=> simple play mode: adjust tempo in 1% steps

TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/ViewMenuItem.java
=> add "Show track table" option in View menu

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/transport/TGTransportDialog.java
This is useful especially in "training" mode, where tempo is increasing at each loop: good to know at what tempo currently playing (and when max tempo is reached)
https://github.com/helge17/tuxguitar/assets/129443524/0b090979-a4ae-4a0d-9788-27ab718f8bf0
Tested on Linux (OpenSuse) and Win10, SWT and JFX
I am not convinced this is the right place to display tempo:
- it makes sense next to a "metronome" icon
- but why in a button?
I think the player dialog could be globally redesigned, this should be considered just a first step
=> in player dialog, display current tempo when playing

TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableHeaderMeasures.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableRowButtonsCell.java, TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java
fix for #53
same logic applied to marker icon for consistency
=> update solo-mute icons in track table when skin changes

TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGDecrementNoteSemitoneAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGIncrementNoteSemitoneAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGTransposeNoteSemitoneAction.java, TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java
it does not make sense to apply action on some notes but not all of them
see [this post](https://github.com/helge17/tuxguitar/discussions/58#discussioncomment-6469635)
=> increment/decrement semitone: all notes or none

TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGShiftNoteAction.java, TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGTransposeNoteSemitoneAction.java, TuxGuitar/src/org/herac/tuxguitar/app/action/listener/cache/controller/TGUpdateNoteRangeController.java
that should be better, see discussion in #75
=> cleanup + play sound only if <=1 beat when shifting up/down

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/transport/TGTransportModeDialog.java
to test:
- select some measures
- type F9 (or menu Player/play mode)
loop range is initialized with measures from selection
=> initialize start/end of training mode with selected measures

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/measure/TGMeasureCopyDialog.java, TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/transport/TGTransportModeDialog.java
see #78 
and a small simplification of previous commit (531495044d70a7e93afb29049527325cfbb7d8c4)
=> initialize copy measure dialog with selected measures numbers

TuxGuitar-android/res/values-b+bg/strings.xml, TuxGuitar-android/res/values-b+ca/strings.xml, TuxGuitar-android/res/values-b+cs/strings.xml, TuxGuitar-android/res/values-b+de/strings.xml, TuxGuitar-android/res/values-b+fi/strings.xml, TuxGuitar-android/res/values-b+fr/strings.xml, TuxGuitar-android/res/values-b+it/strings.xml, TuxGuitar-android/res/values-b+ja/strings.xml, TuxGuitar-android/res/values-b+ko/strings.xml, TuxGuitar-android/res/values-b+lt/strings.xml, TuxGuitar-android/res/values-b+nl/strings.xml, TuxGuitar-android/res/values-b+pl/strings.xml, TuxGuitar-android/res/values-b+ru/strings.xml, TuxGuitar-android/res/values-b+sr/strings.xml, TuxGuitar-android/res/values-b+uk/strings.xml, TuxGuitar-android/res/values-b+vi/strings.xml, TuxGuitar-android/res/values-b+zh+GB/strings.xml, TuxGuitar-android/res/values-b+zh+TW/strings.xml, TuxGuitar-android/res/values-b+zh/strings.xml, TuxGuitar-android/res/values/strings.xml
fix for #88 
in many languages: copied text from action_change_harmonic to harmonic_dlg_title
also corrected a few errors in french version
=> correction of harmonic dialog (Android)

TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP3InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP3OutputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP4InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP4OutputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5OutputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GTPOutputStream.java
=> fix compilation issue

TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5OutputStream.java
should be the last step to fix #109
=> improved import/export of harmonics in gp5 format

TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGMeasureImpl.java, TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGDuration.java
See [request for improvement](https://sourceforge.net/p/tuxguitar/support-requests/16/) in SF
Before:
After:
=> improved representation of tuplets

TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5InputStream.java, TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5OutputStream.java
=> GuitarPro5 Alternative repeats

TuxGuitar-ascii/src/org/herac/tuxguitar/io/ascii/ASCIIOutputStream.java, TuxGuitar-ascii/src/org/herac/tuxguitar/io/ascii/ASCIITabOutputStream.java
=> export dead notes as 'X' in ascii format

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/measure/TGMeasureCleanDialog.java, TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/measure/TGMeasureRemoveDialog.java
In dialogs "clean measure" and "remove measure", measures range is initialized with selection (if something is selected)
see #128
=> initialize range with selection in dialogs

TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiPercussionKey.java
as defined by:
https://en.wikipedia.org/wiki/General_MIDI_Level_2#Additional_percussion_notes
see #131
=> additional percussion sounds in matrix editor

TuxGuitar-android-resources/resources/tunings/tunings.xml, TuxGuitar/share/tunings/tunings.xml
=> correction of "Major Thirds" tuning

TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/track/TGTrackTuningDialog.java
=> TrackTuningDialog: enable checkboxes when selected tuning changes

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/toolbar/main/TGMainToolBarSectionTransport.java
=> add a button in toolbar for player mode

desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/properties/TGFilePropertiesReader.java
=> handle utf8 user config files

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/track/TGTrackPropertiesDialog.java
avoid displaying "null null ..."
=> tracks properties: don't display tuning for percussion channel

desktop/build-scripts/common-resources/common-linux/share/applications/tuxguitar.desktop
=> Fix French translation in tuxguitar.desktop

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/track/TGTrackTuningDialog.java
=> enable trackTuningDialog options when selecting a preset

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableMixer.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java
=> when instruments names change, update volume controls labels

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGShiftNoteAction.java, common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGShiftNoteDownAction.java, common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGShiftNoteUpAction.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java
=> shift up/down: allow even if not possible for all selected notes

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGDrumMap.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGTrackManager.java, common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
when importing midi file
for better readability
see #222
=> arbitrary distribution of percussion to "strings"

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGMeasureHeaderImpl.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGMeasureImpl.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGNoteImpl.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGVoiceImpl.java
partial fix for issue #242: at least notes should not be hidden any more
vertical alignment of beats across tracks remains a complex challenge, since quarters are no more linearly distributed (horizontally) in measures.
also: refactoring (renaming of variables for better readability)
=> fix measure width (bends / multitrack)

doc/contribute.md
Mainly readability updates, including:
- Various typos corrected
- Sentence structure changes for readability
- Line breaks added for readability
- Developer section heading added 
- Maven / Eclipse / TuxGuitar capitalizations
- etc.
=> Contribute page markdown updates

desktop/TuxGuitar-tuner/src/org/herac/tuxguitar/app/tools/custom/tuner/TGTunerFineWidget.java, desktop/TuxGuitar-tuner/src/org/herac/tuxguitar/app/tools/custom/tuner/TGTunerRoughWidget.java, desktop/TuxGuitar-tuner/src/org/herac/tuxguitar/app/tools/custom/tuner/TGTuningString.java
=> fix 1 octave shift in tuner display

common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java, common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
continued
see #256,  764188f336bb27c197d4129edf56973983332cc2
=> rationalize definition of maximum fret number

desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
This adds barline and repeat elements to musicxml export.
=> Added barline and repeat element

android/TuxGuitar-android/res/layout/view_track_tuning_dialog.xml, android/TuxGuitar-android/src/org/herac/tuxguitar/android/view/dialog/track/TGTrackTuningDialog.java
see #280
same modification as cefa9c0273745845cca380847a6aab2e8ba604aa for Android
=> simplify "Change Tuning" dialog

.gitignore, desktop/TuxGuitar/share/help/file_formats.html
Added documentation for MusicXML export. I did edit the html file. If it's generated from an other source, I need to revisit it.
=> Added documentation for MusicXML export

desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
just a first fix.
At least exported file does not violate musicXML schema any more
still TODO: drums track is NOT correctly exported
=> musicXML: don't export tab for drums tracks (meaningless)

common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTrack.java
config management error, pushed the wrong branch :(
=> fix track.isPercussion

desktop/build-scripts/tuxguitar-macosx-jfx-cocoa-x86_64/pom.xml, desktop/build-scripts/tuxguitar-macosx-swt-cocoa-x86_64/pom.xml
see #283
erroneous copy-paste for mac in 24cfd46a62afd1756274eb750ce171d82291e928
=> fix dependency for macOS

desktop/TuxGuitar-fluidsynth/jni/org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth.c
=> fix build error (fluidsynth)

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoard.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoardConfig.java
=> don't display note names on fretboard for percussion tracks

common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/TuningManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/xml/TuningReader.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTuning.java, common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java, common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReaderPlugin.java, desktop/TuxGuitar/share/tunings/tunings.xml
modified:   common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/TuningManager.java
modified:   common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/xml/TuningReader.java
modified:   common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTuning.java
modified:   common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
modified:   desktop/TuxGuitar/share/tunings/tunings.xml
=> Configurable tuning presets in xml file using priority attributes

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/toolbar/edit/TGEditToolBarSectionDuration.java
make graphical representation consistent with behavior:
these items shown in drop-down list do behave like radio buttons
see #333
=> replace checkboxes by radio buttons in "Triplet" drop-down list

desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/file/TGReadURLAction.java
=> don't reopen the same file several times

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/effect/TGChangeAccentuatedNoteAction.java, common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/effect/TGChangeGhostNoteAction.java, common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/effect/TGChangeHeavyAccentuatedNoteAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/effects/TGOpenGraceDialogAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/effects/TGOpenTremoloPickingDialogAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/BeatMenuItem.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/NoteEffectsMenuItem.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/toolbar/edit/TGEditToolBarSectionEffect.java
=> re-enable some effects which are relevant for percussion tracks

common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGTrackManager.java
=> move grace note when one note is re-allocated to another string

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiPlayer.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGBeat.java, desktop/TuxGuitar-test/src/org/herac/tuxguitar/test/TGTestPlayerPosition.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/transport/TGTransport.java
=> set caret position when player stops, considering repeats

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/grace/TGGraceDialog.java
=> Grace note: init dialog with non-zero value, wider range for percussion

desktop/TuxGuitar-test/src/org/herac/tuxguitar/test/TGTestMidiImport.java
=> fix a test

desktop/TuxGuitar/share/lang/messages.properties, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/settings/TGSettingsEditor.java
- typo
- remove unused imports
=> minor fixes

android/TuxGuitar-android-resources/resources/lang
=> common resources: update symlinks for android

desktop/TuxGuitar-converter/src/org/herac/tuxguitar/app/tools/custom/converter/TGConverter.java
required to troubleshoot one user issue
see #380
=> add verbosity

common/TuxGuitar-gpx/src/org/herac/tuxguitar/io/gpx/GPXDocumentParser.java
fix for issue https://github.com/helge17/tuxguitar/discussions/380
=> remove useless cast

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiPlayer.java, desktop/TuxGuitar-tray-swt/src/org/herac/tuxguitar/tray/TGTrayMenu.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/icons/TGIconManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/transport/TGTransportDialog.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/TransportMenuItem.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/toolbar/main/TGMainToolBarSectionTransport.java
see #379
and fix a small bug: text of 1st item of "Player" menu was always "Play"
now it's "Play" or "Pause", considering player status (consistent with associated icon)
=> rationalize player icons

android/TuxGuitar-android/src/org/herac/tuxguitar/android/properties/TGPropertiesImpl.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/util/configuration/TGConfigManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/util/properties/TGProperties.java, desktop/TuxGuitar-synth/src/org/herac/tuxguitar/midi/synth/TGSynthChannelProperties.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigDefaults.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigKeys.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/config/TGConfigManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/properties/TGPropertiesImpl.java
=> Update user config

desktop/TuxGuitar-ui-toolkit-jfx/src/org/herac/tuxguitar/ui/jfx/menu/JFXMenuActionItem.java, desktop/TuxGuitar-ui-toolkit-jfx/src/org/herac/tuxguitar/ui/jfx/menu/JFXMenuCheckableItem.java, desktop/TuxGuitar-ui-toolkit-jfx/src/org/herac/tuxguitar/ui/jfx/menu/JFXMenuRadioItem.java, desktop/TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/menu/SWTMenuActionItem.java, desktop/TuxGuitar-ui-toolkit-swt/src/org/herac/tuxguitar/ui/swt/menu/SWTMenuCheckableItem.java, desktop/TuxGuitar-ui-toolkit/src/org/herac/tuxguitar/ui/menu/UIMenuCheckableItem.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/toolbar/edit/TGEditToolBarSectionDuration.java
=> fix tuplets issue

desktop/TuxGuitar/share/lang, desktop/TuxGuitar/share/templates, desktop/TuxGuitar/share/tunings, desktop/build-scripts/tuxguitar-freebsd-jfx/pom.xml, desktop/build-scripts/tuxguitar-freebsd-swt/pom.xml, desktop/build-scripts/tuxguitar-linux-jfx/pom.xml, desktop/build-scripts/tuxguitar-linux-swt/pom.xml, desktop/build-scripts/tuxguitar-macosx-jfx-cocoa/pom.xml, desktop/build-scripts/tuxguitar-macosx-swt-cocoa/pom.xml, desktop/build-scripts/tuxguitar-windows-jfx-x86_64/pom.xml, desktop/build-scripts/tuxguitar-windows-swt-x86_64/pom.xml
cleaner
and easier to package with rpmbuild
=> common resources: replace symlinks by build instructions

desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
see #289
non-percussion tracks: publish score and tablature as 2 staffs in 1 single track
percussion tracks: correct clef
bass clef: explicit 1-octave shift
=> improve musicXML export

android/TuxGuitar-android/res/values-b+pl/strings.xml
Update Polish Translation (Android)
Greetings,
Gootector
=> Update Polish Translation (Android)

website/style.css
Fixes in style.css
Greetings,
Gootector
=> Fixes in style.css

desktop/TuxGuitar/share/scales/scales.xml
Fixes in scales.xml
Greetings,
Gootector
=> Fixes in scales.xml

desktop/TuxGuitar/share/scales/scales.xml, website/style.css
Fixes in scales.xml and style.css
Greetings,
Gootector
=> Fixes in scales.xml and style.css

INSTALL.md, desktop/TuxGuitar-test/pom.xml, desktop/TuxGuitar-ui-toolkit/src/org/herac/tuxguitar/ui/widget/UIScrollBar.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TGControl.java, desktop/pom.xml, doc/contribute.md, misc/build_tuxguitar_from_source.sh
see issue #403 
This PR supersedes PR #423
@helge17 : sorry to ask for your help again, could you please check how it behaves on macOS?
I could test this PR on Win10, Linux and FreeBSD.
Now the scrollbars should be hidden when playing, and also when useless (e.g. horizontal scrollbar in page mode)
=> Perf optimization, update SWT for Linux to 4.26

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/chord/TGChordDialog.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/chord/TGChordSelector.java
=> Consider current key signature when opening chord editor

common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGNoteImpl.java
=> draw dead notes in score

android/TuxGuitar-android/res/values/strings.xml
Missing tuplets
https://en.m.wiktionary.org/wiki/decuplet
Greetings,
Gootector
=> Missing tuplets

README.md, doc/contribute.md
Fixes in README.md and contribute.md
Greetings,
Gootector
=> Fixes in README.md and contribute.md

doc/contribute.md
Fixes in contribute.md
A few fixes I missed.
Greetings,
Gootector
=> Fixes in contribute.md

common/TuxGuitar-lib/src/org/herac/tuxguitar/util/TGMessagesManager.java
=> fix displayed message with apostrophe and parameter

common/TuxGuitar-compat/src/org/herac/tuxguitar/io/tg/TGAbstractSongReaderPlugin.java, common/TuxGuitar-compat/src/org/herac/tuxguitar/io/tg/TGAbstractSongWriterPlugin.java, common/TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GTPOutputStreamPlugin.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/io/base/TGFileFormatManager.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/io/plugin/TGSongWriterPlugin.java, common/TuxGuitar-lilypond/src/org/herac/tuxguitar/io/lilypond/LilypondSongWriterPlugin.java, common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongWriterPlugin.java, common/TuxGuitar-pdf/src/org/herac/tuxguitar/io/pdf/PDFSongWriterPlugin.java, desktop/TuxGuitar-ascii/src/org/herac/tuxguitar/io/ascii/ASCIISongWriterPlugin.java, desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLSongWriterPlugin.java, desktop/TuxGuitar-svg/src/org/herac/tuxguitar/io/svg/SVGSongWriterPlugin.java, desktop/TuxGuitar-synth-export/src/org/herac/tuxguitar/io/synth/TGSynthSongWriterPlugin.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/file/TGWriteFileAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/file/TGFileChooserDialog.java
See #462, and [this post](https://github.com/helge17/tuxguitar/pull/470#issuecomment-2246236013) in #470
@helge17: this should be close to your proposal. I would appreciate some more testing if you can.
=> Foreign formats

desktop/TuxGuitar-synth/src/org/herac/tuxguitar/midi/synth/ui/TGSynthDialog.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/chord/TGChordSettingsDialog.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/track/TGTrackTuningChooserDialog.java
This fix added missing colons in:
* the Track menu -> Properties:
-- Instrument Settings -> Settings - two options with "+";
-- Tuning Settings -> "+";
* the Beat menu -> Chord -> Insert Chord -> Settings.
Greetings,
Gootector
=> Missing colons

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/fretboard/TGFretBoard.java
=> added buttons to configure fretboard height

common/resources/lang/messages_pl.properties
Update Polish Translation (new strings)
Greetings,
Gootector
=> Update Polish Translation (new strings)

common/TuxGuitar-gpx/src/org/herac/tuxguitar/io/gpx/GPXDocumentParser.java, common/TuxGuitar-gpx/src/org/herac/tuxguitar/io/gpx/GPXDocumentReader.java, common/TuxGuitar-gpx/src/org/herac/tuxguitar/io/gpx/score/GPXDocument.java, common/TuxGuitar-gpx/src/org/herac/tuxguitar/io/gpx/score/GPXMasterBar.java
see #102
- when importing .gp file, try to guess percussion/non-percussion track attribute when gm channels are undefined
- import markers
=> improvement of gp import

desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/file/TGWriteFileAction.java
see 587d9b81c5ec000df43cd98351d2192c7a0004a5
when exporting under old tg format, don't update current doc uri, don't consider current doc saved
should fix issue #501
=> don't change current doc uri when exporting song (continued)

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiSequenceParser.java
=> fix issue with letRing and tied notes

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiSequenceParser.java
see #258
stop letRing when
- one note does not have letRing effect
- changing measure, with a non-tied note in new measure
=> limit letRing duration

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TGControl.java
=> fix one scrolling issue

desktop/TuxGuitar/share/help/detail_measure_beat.html, desktop/TuxGuitar/share/help/tools_shortcuts.html
added one default keyboard shortcut
fixed a typo
=> minor doc fix

doc/contribute.md
Missing dot 😉
Greetings,
Gootector
=> Fix: missing dot

common/TuxGuitar-editor-utils/src/org/herac/tuxguitar/editor/action/note/TGInsertChordAction.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGVoice.java
=> chord selection adds chord to tab even if selected beat is not a rest

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/TGControl.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Tablature.java
side effect #536
This reverts commit db7b368f5577118e35007045946d6a5bccffbd26.
=> Revert "fix one scrolling issue"

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/table/TGTableViewer.java
=> fix track table refresh issue on Windows

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiRepeatController.java
to reproduce:
- create a song where measures belong to several alt repeat
- define a loop starting with the following alt repeat
- play => player gets stuck
see #549
=> fix bug with loop and multiple alternative repeat

desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/keybindings/KeyBindingActionManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/system/keybindings/xml/KeyBindingWriter.java
so that a default shortcut introduced by an app upgrade is correctly considered
fix #553
=> merge default and user-defined shortcuts

desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Tablature.java
=> display loop markers if "from beginning" or "to the end"

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiSequenceParser.java
=> midi and audio export: only audible tracks

desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/transport/TGTransportSetLoopEHeaderAction.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/transport/TGTransportSetLoopSHeaderAction.java
for consistency with 9c77cb7ffc0f0b0ff44ed6a887b5fedfacc75c10
fix following user feedback after testing 1.6.5beta1
=> save loop start/end into document when set by "Player" menu

desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/TEInputStream.java, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/TESongParser.java, desktop/TuxGuitar-tef/src/org/herac/tuxguitar/io/tef/base/TEComponentNote.java
Addresses an issue when importing v2 TEF files where techniques, and dynamics were not being imported.
Changes include:
- Dynamics
- Hammer On
- Pull Off
- Natural Harmonic
- Artificial Harmonic
- Palm Mute
- Tapping
- Vibrato
- Tremolo (only 1 duration though. No metadata for duration)
- Bend / Bend + Release
- Let Ring
- Slap
- Ghost Note
- Staccato
- Fade In
=> #471 Adds better technique importing for v2 TEF files

android/TuxGuitar-android/src/org/herac/tuxguitar/android/view/dialog/grace/TGGraceDialog.java, common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/io/tg/TGStream.java, common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/song/models/effects/TGEffectGrace.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/grace/TGGraceDialog.java
=> fix grace note duration inconsistency between android and desktop

common/TuxGuitar-lib/src/org/herac/tuxguitar/player/base/MidiSequenceParser.java
bug introduced by 2b1111ee4267ca9132e36c873eef0ba88d51019c
many possible consequences when first track is muted: erroneous tempo, no metronome,...
see #606, #607
=> fix several issues when first track is muted

common/resources/lang/messages_pl.properties
Update Polish translation
Greetings,
Gootector
=> Update Polish translation

common/TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP4OutputStream.java, common/TuxGuitar-gtp/src/org/herac/tuxguitar/io/gtp/GP5OutputStream.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGChordImpl.java, common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGMeasureManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/chord/TGChordEditor.java
=> fix too wide chord diagrams

desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/installer/TGActionConfigMap.java
=> add keyboard shortcut for "open repeat"

android/TuxGuitar-android/res/menu/menu_selected_beat.xml, android/TuxGuitar-android/res/menu/menu_selected_note.xml, android/TuxGuitar-android/src/org/herac/tuxguitar/android/menu/controller/impl/smart/TGSelectedNoteMenu.java
trying to fix issue #659 
@helge17 , could you please check if it's OK?
I've got serious problems in my AndroidStudio configuration, for an unknown reason I'm constantly loosing communication with virtual device, so it's not so easy for me to test :(
=> fix android issue, long tap on empty position

doc/contribute.md, misc/tuxguitar_formatting.xml
=> code style formatting configuration

desktop/TuxGuitar/src/org/herac/tuxguitar/app/action/impl/edit/TGPasteAction.java
=> paste with active selection: paste at selection start

common/TuxGuitar-lib/src/main/java/org/herac/tuxguitar/song/managers/TGSongManager.java, desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/menu/impl/EditMenuItem.java
=> Free edition mode

android/TuxGuitar-android/src/app/tuxguitar/android/view/tablature/TGCaret.java, android/TuxGuitar-android/src/app/tuxguitar/android/view/tablature/TGSongViewStyles.java, common/TuxGuitar-editor-utils/src/app/tuxguitar/editor/action/duration/TGSetDurationAction.java, common/TuxGuitar-editor-utils/src/app/tuxguitar/editor/action/note/TGDeleteNoteOrRestAction.java
TGCaret: fix move left/move right
TGSongViewStyles: red lines for invalid measures
TGSetDurationAction, TGDeleteNoteOrRestAction: bug fix
=> free edition mode, fix android

desktop/TuxGuitar/src/app/tuxguitar/app/action/impl/selector/TGUpdateDragSelectionAction.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/component/tab/Selector.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/component/tab/edit/EditorKit.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/component/tab/edit/MouseKit.java
=> sensitivity of click & drag

android/TuxGuitar-android/res/menu/menu_measure.xml, android/TuxGuitar-android/res/values-b+fr/strings.xml, android/TuxGuitar-android/res/values/strings.xml, android/TuxGuitar-android/src/app/tuxguitar/android/action/installer/TGActionConfigMap.java, android/TuxGuitar-android/src/app/tuxguitar/android/action/installer/TGActionInstaller.java, android/TuxGuitar-android/src/app/tuxguitar/android/menu/controller/impl/contextual/TGMeasureMenu.java, common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/helpers/TGMeasureError.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/errors/TGMeasureErrorDialog.java
android: add "Fix voice" action in measure menu
=> Free edition mode (android)

AUTHORS, desktop/TuxGuitar/share/help/about.html
Fixes in AUTHORS.txt and about.html:
- missing "Contact: "
- unnecessary space
Greetings,
Grzegorz
=> Fixes in AUTHORS.txt and about.html

desktop/TuxGuitar/src/app/tuxguitar/app/action/installer/TGActionConfigMap.java
=> bug fix, graphical elements erroneously repeated

common/TuxGuitar-editor-utils/src/app/tuxguitar/editor/action/measure/TGRemoveUnusedVoiceAction.java
was broken by d1d3e4afb8f7116a1ba234fdcbeb6d802194d5bb
=> fix "remove unused voice" on Android

desktop/TuxGuitar/src/app/tuxguitar/app/view/menu/impl/BeatMenuItem.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/toolbar/edit/TGEditToolBarSectionBeat.java
most often, pick stroke down is used first
=> swap places of pickStroke up/down in toolbar and menu

common/TuxGuitar-lib/src/main/java/app/tuxguitar/graphics/control/TGMeasureImpl.java
when a measure is invalid
fix #727
=> free edition mode, fix display if not in compact mode

desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/errors/TGMeasureErrorDialog.java
=> clear selection when fixing a measure

common/TuxGuitar-editor-utils/src/app/tuxguitar/editor/action/measure/TGFixMeasureVoiceAction.java, common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/helpers/TGMeasureError.java, common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/managers/TGMeasureManager.java, common/TuxGuitar-lib/src/test/java/app/tuxguitar/song/managers/TestFreeEditionMode.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/errors/TGMeasureErrorDialog.java
=> Fix overlap

common/TuxGuitar-editor-utils/src/app/tuxguitar/editor/action/composition/TGChangeKeySignatureAction.java, common/TuxGuitar-lib/src/main/java/app/tuxguitar/song/managers/TGTrackManager.java, common/resources/lang/messages.properties, common/resources/lang/messages_bg.properties, common/resources/lang/messages_ca.properties, common/resources/lang/messages_cs.properties, common/resources/lang/messages_de.properties, common/resources/lang/messages_el.properties, common/resources/lang/messages_es.properties, common/resources/lang/messages_eu.properties, common/resources/lang/messages_fi.properties, common/resources/lang/messages_fr.properties, common/resources/lang/messages_hu.properties, common/resources/lang/messages_it.properties, common/resources/lang/messages_ja.properties, common/resources/lang/messages_ko.properties, common/resources/lang/messages_lt.properties, common/resources/lang/messages_nl.properties, common/resources/lang/messages_pl.properties, common/resources/lang/messages_pt.properties, common/resources/lang/messages_ru.properties, common/resources/lang/messages_sr.properties, common/resources/lang/messages_sv.properties, common/resources/lang/messages_uk.properties, common/resources/lang/messages_vi.properties, common/resources/lang/messages_zh.properties, common/resources/lang/messages_zh_GB.properties, common/resources/lang/messages_zh_TW.properties, desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/keysignature/TGKeySignatureDialog.java
=> apply key signature to selection

desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java
This is my attempt to correctly export ties in MusicXML using the newly implemented `isAnyTiedTo` function. 
Please test. If you're happy with this, we can replace the method from the LilyPond exporter in the next step.
=> [MusicXML] add tie start and notation

.github/workflows/android-gradle.yml
Please find an Android CI to build TuxGuitar. Merge this PR if its helps, I do not use Android myself so I am unable to test.
Java version 21 is selected but it may not be the accurate one.
=> Create a GitHub Action to build  for Android

desktop/TuxGuitar/src/app/tuxguitar/app/view/component/tab/Caret.java
caret was left out of the song
see #758
=> fix issue when deleting last measure in free edition mode

desktop/TuxGuitar/src/app/tuxguitar/app/view/component/tab/Selector.java
=> force selection break over the frontier of an invalid measure

desktop/TuxGuitar-ui-toolkit-swt/src/app/tuxguitar/ui/swt/widget/SWTLayoutContainer.java
=> Workaround for incorrect dialog display on macOS

common/TuxGuitar-gpx/src/app/tuxguitar/io/gpx/GPXDocumentParser.java
=> fix gpx import

desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/browser/main/TGBrowserDialog.java
another attempt following 93e639585ae07b16b5b974b29048fe6be9db93a9
see #791
=> workaround for a SWT issue

desktop/TuxGuitar/src/app/tuxguitar/app/view/toolbar/main/TGMainToolBar.java
to reproduce issue:
put only one tempo indicator plus one standard button in left area
=> fix toolbar alignment issue

desktop/TuxGuitar/share/skins/Breeze-dark/skin.prop, desktop/TuxGuitar/share/skins/Breeze/skin.prop, desktop/TuxGuitar/share/skins/Oxygen-dark/skin.prop, desktop/TuxGuitar/share/skins/Oxygen/skin.prop, desktop/TuxGuitar/share/skins/Symbolic-dark/skin.prop, desktop/TuxGuitar/share/skins/Symbolic/skin.prop, desktop/TuxGuitar/src-skins/Breeze/TuxGuitar/skin-dark.prop, desktop/TuxGuitar/src-skins/Breeze/TuxGuitar/skin.prop, desktop/TuxGuitar/src/app/tuxguitar/app/view/component/table/TGTableCanvasPainter.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/component/table/TGTableColorModel.java
else caret is not visible when track color is dark (#813)
also: use rounded rectangle
=> adapt caret color in track table according to background

desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/piano/TGPiano.java
This is a pull request only for the piano fixes:
- Click area fixed.
- Drawing order fixed (this simply changes the place of line 247).
This does not include the identification of octaves.
=> Piano fixes: click area and drawing order

common/TuxGuitar-ptb/src/app/tuxguitar/io/ptb/PTInputStream.java
Fix: PowerTab -> Power Tab Editor
https://en.wikipedia.org/wiki/Power_Tab_Editor
Greetings,
Grzegorz
=> Fix: PowerTab -> Power Tab Editor

desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/track/TGTrackPropertiesDialog.java
=> track properties, ignore empty instrument selection

common/resources/lang/messages_bg.properties, common/resources/lang/messages_ca.properties, common/resources/lang/messages_cs.properties, common/resources/lang/messages_de.properties, common/resources/lang/messages_el.properties, common/resources/lang/messages_eu.properties, common/resources/lang/messages_fi.properties, common/resources/lang/messages_fr.properties, common/resources/lang/messages_hu.properties, common/resources/lang/messages_it.properties, common/resources/lang/messages_ja.properties, common/resources/lang/messages_ko.properties, common/resources/lang/messages_lt.properties, common/resources/lang/messages_nl.properties, common/resources/lang/messages_pl.properties, common/resources/lang/messages_pt.properties, common/resources/lang/messages_ru.properties, common/resources/lang/messages_sr.properties, common/resources/lang/messages_sv.properties, common/resources/lang/messages_uk.properties, common/resources/lang/messages_vi.properties, common/resources/lang/messages_zh_CN.properties, common/resources/lang/messages_zh_TW.properties
and add ids of new strings to translate in other languages
=> update fr translation

desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/piano/TGPiano.java
=> minor cleanup

README.md, misc/build_tuxguitar_from_source.sh
Typos in build_tuxguitar_from_source.sh & README.md
=> Typos in build_tuxguitar_from_source.sh & README.md

common/TuxGuitar-gpx/src/app/tuxguitar/io/gpx/GPXDocumentReader.java
some .gp files produced by songsterr have line breaks in track names :(
fix #883
=> adaptation to some (weird) gp files

desktop/TuxGuitar-ui-toolkit-jfx/src/app/tuxguitar/ui/jfx/widget/JFXWindow.java
=> jfx, fix unexpected resizable windows

desktop/TuxGuitar-ui-toolkit-jfx/src/app/tuxguitar/ui/jfx/widget/JFXWindow.java, desktop/TuxGuitar-ui-toolkit-swt/src/app/tuxguitar/ui/swt/widget/SWTWindow.java, desktop/TuxGuitar-ui-toolkit/src/app/tuxguitar/ui/widget/UIWindow.java, desktop/TuxGuitar/src/app/tuxguitar/app/view/dialog/marker/TGMarkerList.java
=> resizable marker list dialog

common/TuxGuitar-lib/src/main/java/app/tuxguitar/graphics/control/TGMeasureImpl.java
continuation of 7e5e373241c41b066a8b0ec7cc05c34984c4c45b
fixes #911
=> fix tuplets representation

android/TuxGuitar-android/res/values-b+bg/strings.xml, android/TuxGuitar-android/res/values-b+ru/strings.xml
Specify "to the next **Tempo** Marker"  for BG and RU translations due to #906.
=> Update RU, BG translation for "apply tempo to marker" action
